import { useEffect, useState } from 'react';
import { Query } from 'appwrite';
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  faFileLines, faFilePdf, faImage as faImageIcon, faVideo, faRobot, faCode,
  faGraduationCap, faChartBar, faPenNib, faDatabase, faFileWord, faFileExcel,
  faFilePowerpoint, faCompress, faScissors, faCut, faRotate, faShield, faLock,
  faUnlock, faMagnifyingGlass, faWater, faListOl, faObjectUngroup, faExpand,
  faDroplet, faTools, faFolder, faCog, faBroom, faCrop, faImage,
  faFileZipper, faKey, faEye, faBolt, faPen, faEyeSlash, faStar,
  faLayerGroup, faCompressArrowsAlt, faColumns, faAlignLeft,
  faFileCode, faFloppyDisk, faArrowsAlt, faFileMedical, faBriefcase, faPalette,
  faRotateRight, faArrowsLeftRight, faWandMagicSparkles, faSun, faCircleHalfStroke, faShieldHalved, faFileImage,
  faMusic, faVolumeXmark, faTachometerAlt, faBackward, faRepeat, faFilm, faGaugeHigh, faClosedCaptioning, faTv, faImages, faSliders
, faVolumeHigh} from '@fortawesome/free-solid-svg-icons';
import { DATABASE_ID, databases, isAppwriteConfigured } from './qofeno-appwrite';

export interface ToolCard {
  id: string;
  slug: string;
  name: string;
  category: string;
  subcategory: string;
  type: 'Free' | 'Pro';
  isNew?: boolean;
  addedAt?: string;
  isPopular: boolean;
  runs: string;
  desc: string;
  icon: IconDefinition;
  imageUrl: string | null;
  schemaMarkup: string;
  functionId?: string;
  tags?: string[];
}

export interface CategoryCard {
  name: string;
  count: number;
  sub?: string[];
}

export interface ToolCatalogState {
  tools: ToolCard[];
  featuredTools: ToolCard[];
  categoryCards: CategoryCard[];
  loading: boolean;
}

const TOOL_ICON_MAP: Record<string, IconDefinition> = {
  'PDF & Documents': faFilePdf,
  'Image Tools': faImageIcon,
  'Video Tools': faVideo,
  'AI & Automation': faRobot,
  'Developer Tools': faCode,
  'Data Tools': faChartBar,
  'Study Tools': faGraduationCap,
  'Writing Tools': faPenNib,
};

export const FALLBACK_TOOLS: ToolCard[] = [
  {
    id: 'audio-manipulator',
    slug: 'audio-manipulator',
    name: 'Audio Manipulator',
    category: 'Audio Tools',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Audio Manipulator tool running directly in your browser or securely on our servers.',
    icon: faMusic,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Audio Manipulator',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Audio Manipulator tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_AUDIO_MANIPULATOR_ID || 'audio-manipulator',
  },
  {
    id: 'base64-encoder',
    slug: 'base64-encoder',
    name: 'Base64 Encoder',
    category: 'Developer Tools',
    subcategory: 'Utilities',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Base64 Encoder tool running directly in your browser or securely on our servers.',
    icon: faCode,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Base64 Encoder',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Base64 Encoder tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_BASE64_ENCODER_ID || 'base64-encoder',
  },
  {
    id: 'batch-compress-pdfs',
    slug: 'batch-compress-pdfs',
    name: 'Batch Compress PDFs',
    category: 'PDF & Documents',
    subcategory: 'Compressors',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Batch Compress PDFs tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Batch Compress PDFs',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Batch Compress PDFs tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_BATCH_COMPRESS_PDFS_ID || 'batch-compress-pdfs',
  },
  {
    id: 'batch-convert-pdfs',
    slug: 'batch-convert-pdfs',
    name: 'Batch Convert PDFs',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Batch Convert PDFs tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Batch Convert PDFs',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Batch Convert PDFs tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_BATCH_CONVERT_PDFS_ID || 'batch-convert-pdfs',
  },
  {
    id: 'batch-merge-pdfs',
    slug: 'batch-merge-pdfs',
    name: 'Batch Merge PDFs',
    category: 'PDF & Documents',
    subcategory: 'Combiners',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Batch Merge PDFs tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Batch Merge PDFs',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Batch Merge PDFs tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_BATCH_MERGE_PDFS_ID || 'batch-merge-pdfs',
  },
  {
    id: 'excel-to-pdf',
    slug: 'excel-to-pdf',
    name: 'Excel To PDF',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Excel To PDF tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Excel To PDF',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Excel To PDF tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_EXCEL_TO_PDF_ID || 'excel-to-pdf',
  },
  {
    id: 'image-bg-remover',
    slug: 'image-bg-remover',
    name: 'Image Background Remover',
    category: 'Image Tools',
    subcategory: 'Utilities',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Image Background Remover tool running directly in your browser or securely on our servers.',
    icon: faImageIcon,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Image Background Remover',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Image Background Remover tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_IMAGE_BG_REMOVER_ID || 'image-bg-remover',
  },
  {
    id: 'image-compressor',
    slug: 'image-compressor',
    name: 'Image Compressor',
    category: 'Image Tools',
    subcategory: 'Compressors',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Image Compressor tool running directly in your browser or securely on our servers.',
    icon: faImageIcon,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Image Compressor',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Image Compressor tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_IMAGE_COMPRESSOR_ID || 'image-compressor',
  },
  {
    id: 'image-converter',
    slug: 'image-converter',
    name: 'Image Converter',
    category: 'Image Tools',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Image Converter tool running directly in your browser or securely on our servers.',
    icon: faImageIcon,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Image Converter',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Image Converter tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_IMAGE_CONVERTER_ID || 'image-converter',
  },
  {
    id: 'image-manipulator',
    slug: 'image-manipulator',
    name: 'Image Manipulator',
    category: 'Image Tools',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Image Manipulator tool running directly in your browser or securely on our servers.',
    icon: faImageIcon,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Image Manipulator',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Image Manipulator tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_IMAGE_MANIPULATOR_ID || 'image-manipulator',
  },
  {
    id: 'image-resizer',
    slug: 'image-resizer',
    name: 'Image Resizer',
    category: 'Image Tools',
    subcategory: 'Resizers',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Image Resizer tool running directly in your browser or securely on our servers.',
    icon: faImageIcon,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Image Resizer',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Image Resizer tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_IMAGE_RESIZER_ID || 'image-resizer',
  },
  {
    id: 'jpg-to-pdf',
    slug: 'jpg-to-pdf',
    name: 'JPG To PDF',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality JPG To PDF tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'JPG To PDF',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality JPG To PDF tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_JPG_TO_PDF_ID || 'jpg-to-pdf',
  },
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    name: 'JSON Formatter',
    category: 'Developer Tools',
    subcategory: 'Utilities',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality JSON Formatter tool running directly in your browser or securely on our servers.',
    icon: faCode,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'JSON Formatter',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality JSON Formatter tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_JSON_FORMATTER_ID || 'json-formatter',
  },
  {
    id: 'pdf-booklet-creator',
    slug: 'pdf-booklet-creator',
    name: 'PDF Booklet Creator',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Booklet Creator tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Booklet Creator',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Booklet Creator tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_BOOKLET_CREATOR_ID || 'pdf-booklet-creator',
  },
  {
    id: 'pdf-color-converter',
    slug: 'pdf-color-converter',
    name: 'PDF Color Converter',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Color Converter tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Color Converter',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Color Converter tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_COLOR_CONVERTER_ID || 'pdf-color-converter',
  },
  {
    id: 'pdf-compare',
    slug: 'pdf-compare',
    name: 'PDF Compare',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Pro',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Compare tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Compare',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Compare tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_COMPARE_ID || 'pdf-compare',
  },
  {
    id: 'pdf-compressor',
    slug: 'pdf-compressor',
    name: 'PDF Compressor',
    category: 'PDF & Documents',
    subcategory: 'Compressors',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Compressor tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Compressor',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Compressor tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_COMPRESSOR_ID || 'pdf-compressor',
  },
  {
    id: 'pdf-crop',
    slug: 'pdf-crop',
    name: 'PDF Crop',
    category: 'PDF & Documents',
    subcategory: 'Resizers',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Crop tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Crop',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Crop tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_CROP_ID || 'pdf-crop',
  },
  {
    id: 'pdf-delete-pages',
    slug: 'pdf-delete-pages',
    name: 'PDF Delete Pages',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Delete Pages tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Delete Pages',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Delete Pages tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_DELETE_PAGES_ID || 'pdf-delete-pages',
  },
  {
    id: 'pdf-extract-pages',
    slug: 'pdf-extract-pages',
    name: 'PDF Extract Pages',
    category: 'PDF & Documents',
    subcategory: 'Separators',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Extract Pages tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Extract Pages',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Extract Pages tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_EXTRACT_PAGES_ID || 'pdf-extract-pages',
  },
  {
    id: 'pdf-flatten',
    slug: 'pdf-flatten',
    name: 'PDF Flatten',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Flatten tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Flatten',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Flatten tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_FLATTEN_ID || 'pdf-flatten',
  },
  {
    id: 'pdf-form-creator',
    slug: 'pdf-form-creator',
    name: 'PDF Form Creator',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Form Creator tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Form Creator',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Form Creator tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_FORM_CREATOR_ID || 'pdf-form-creator',
  },
  {
    id: 'pdf-form-filler',
    slug: 'pdf-form-filler',
    name: 'PDF Form Filler',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Form Filler tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Form Filler',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Form Filler tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_FORM_FILLER_ID || 'pdf-form-filler',
  },
  {
    id: 'pdf-grayscale',
    slug: 'pdf-grayscale',
    name: 'PDF Grayscale',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Grayscale tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Grayscale',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Grayscale tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_GRAYSCALE_ID || 'pdf-grayscale',
  },
  {
    id: 'pdf-header-footer',
    slug: 'pdf-header-footer',
    name: 'PDF Header Footer',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Header Footer tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Header Footer',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Header Footer tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_HEADER_FOOTER_ID || 'pdf-header-footer',
  },
  {
    id: 'pdf-merger',
    slug: 'pdf-merger',
    name: 'PDF Merger',
    category: 'PDF & Documents',
    subcategory: 'Combiners',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Merger tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Merger',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Merger tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_MERGER_ID || 'pdf-merger',
  },
  {
    id: 'pdf-metadata-editor',
    slug: 'pdf-metadata-editor',
    name: 'PDF Metadata Editor',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Metadata Editor tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Metadata Editor',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Metadata Editor tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_METADATA_EDITOR_ID || 'pdf-metadata-editor',
  },
  {
    id: 'pdf-metadata-viewer',
    slug: 'pdf-metadata-viewer',
    name: 'PDF Metadata Viewer',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Metadata Viewer tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Metadata Viewer',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Metadata Viewer tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_METADATA_VIEWER_ID || 'pdf-metadata-viewer',
  },
  {
    id: 'pdf-ocr',
    slug: 'pdf-ocr',
    name: 'PDF OCR',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Pro',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF OCR tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF OCR',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF OCR tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_OCR_ID || 'pdf-ocr',
  },
  {
    id: 'pdf-page-extractor-bulk',
    slug: 'pdf-page-extractor-bulk',
    name: 'PDF Page Extractor Bulk',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Page Extractor Bulk tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Page Extractor Bulk',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Page Extractor Bulk tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_PAGE_EXTRACTOR_BULK_ID || 'pdf-page-extractor-bulk',
  },
  {
    id: 'pdf-page-number-customizer',
    slug: 'pdf-page-number-customizer',
    name: 'PDF Page Number Customizer',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Page Number Customizer tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Page Number Customizer',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Page Number Customizer tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_PAGE_NUMBER_CUSTOMIZER_ID || 'pdf-page-number-customizer',
  },
  {
    id: 'pdf-page-numbers',
    slug: 'pdf-page-numbers',
    name: 'PDF Page Numbers',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Page Numbers tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Page Numbers',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Page Numbers tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_PAGE_NUMBERS_ID || 'pdf-page-numbers',
  },
  {
    id: 'pdf-portfolio-creator',
    slug: 'pdf-portfolio-creator',
    name: 'PDF Portfolio Creator',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Portfolio Creator tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Portfolio Creator',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Portfolio Creator tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_PORTFOLIO_CREATOR_ID || 'pdf-portfolio-creator',
  },
  {
    id: 'pdf-protect',
    slug: 'pdf-protect',
    name: 'PDF Protect',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Pro',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Protect tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Protect',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Protect tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_PROTECT_ID || 'pdf-protect',
  },
  {
    id: 'pdf-redact',
    slug: 'pdf-redact',
    name: 'PDF Redact',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Redact tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Redact',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Redact tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_REDACT_ID || 'pdf-redact',
  },
  {
    id: 'pdf-reorder-pages',
    slug: 'pdf-reorder-pages',
    name: 'PDF Reorder Pages',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Reorder Pages tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Reorder Pages',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Reorder Pages tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_REORDER_PAGES_ID || 'pdf-reorder-pages',
  },
  {
    id: 'pdf-repair',
    slug: 'pdf-repair',
    name: 'PDF Repair',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Pro',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Repair tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Repair',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Repair tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_REPAIR_ID || 'pdf-repair',
  },
  {
    id: 'pdf-resize',
    slug: 'pdf-resize',
    name: 'PDF Resize',
    category: 'PDF & Documents',
    subcategory: 'Resizers',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Resize tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Resize',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Resize tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_RESIZE_ID || 'pdf-resize',
  },
  {
    id: 'pdf-rotate',
    slug: 'pdf-rotate',
    name: 'PDF Rotate',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Rotate tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Rotate',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Rotate tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_ROTATE_ID || 'pdf-rotate',
  },
  {
    id: 'pdf-sign',
    slug: 'pdf-sign',
    name: 'PDF Sign',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Pro',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Sign tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Sign',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Sign tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_SIGN_ID || 'pdf-sign',
  },
  {
    id: 'pdf-splitter',
    slug: 'pdf-splitter',
    name: 'PDF Splitter',
    category: 'PDF & Documents',
    subcategory: 'Separators',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Splitter tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Splitter',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Splitter tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_SPLITTER_ID || 'pdf-splitter',
  },
  {
    id: 'pdf-thumbnail',
    slug: 'pdf-thumbnail',
    name: 'PDF Thumbnail',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Thumbnail tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Thumbnail',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Thumbnail tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_THUMBNAIL_ID || 'pdf-thumbnail',
  },
  {
    id: 'pdf-to-excel',
    slug: 'pdf-to-excel',
    name: 'PDF To Excel',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF To Excel tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF To Excel',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF To Excel tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_TO_EXCEL_ID || 'pdf-to-excel',
  },
  {
    id: 'pdf-to-html',
    slug: 'pdf-to-html',
    name: 'PDF To HTML',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF To HTML tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF To HTML',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF To HTML tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_TO_HTML_ID || 'pdf-to-html',
  },
  {
    id: 'pdf-to-jpg',
    slug: 'pdf-to-jpg',
    name: 'PDF To JPG',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF To JPG tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF To JPG',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF To JPG tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_TO_JPG_ID || 'pdf-to-jpg',
  },
  {
    id: 'pdf-to-powerpoint',
    slug: 'pdf-to-powerpoint',
    name: 'PDF To Powerpoint',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF To Powerpoint tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF To Powerpoint',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF To Powerpoint tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_TO_POWERPOINT_ID || 'pdf-to-powerpoint',
  },
  {
    id: 'pdf-to-text',
    slug: 'pdf-to-text',
    name: 'PDF To Text',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF To Text tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF To Text',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF To Text tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_TO_TEXT_ID || 'pdf-to-text',
  },
  {
    id: 'pdf-to-word',
    slug: 'pdf-to-word',
    name: 'PDF To Word',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF To Word tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF To Word',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF To Word tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_TO_WORD_ID || 'pdf-to-word',
  },
  {
    id: 'pdf-unlock',
    slug: 'pdf-unlock',
    name: 'PDF Unlock',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Pro',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Unlock tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Unlock',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Unlock tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_UNLOCK_ID || 'pdf-unlock',
  },
  {
    id: 'pdf-watermark',
    slug: 'pdf-watermark',
    name: 'PDF Watermark',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Pro',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Watermark tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Watermark',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Watermark tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_WATERMARK_ID || 'pdf-watermark',
  },
  {
    id: 'pdf-word-count',
    slug: 'pdf-word-count',
    name: 'PDF Word Count',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality PDF Word Count tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'PDF Word Count',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality PDF Word Count tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_PDF_WORD_COUNT_ID || 'pdf-word-count',
  },
  {
    id: 'powerpoint-to-pdf',
    slug: 'powerpoint-to-pdf',
    name: 'Powerpoint To PDF',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Powerpoint To PDF tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Powerpoint To PDF',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Powerpoint To PDF tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_POWERPOINT_TO_PDF_ID || 'powerpoint-to-pdf',
  },
  {
    id: 'text-case-converter',
    slug: 'text-case-converter',
    name: 'Text Case Converter',
    category: 'Developer Tools',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Text Case Converter tool running directly in your browser or securely on our servers.',
    icon: faCode,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Text Case Converter',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Text Case Converter tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_TEXT_CASE_CONVERTER_ID || 'text-case-converter',
  },
  {
    id: 'video-compressor',
    slug: 'video-compressor',
    name: 'Video Compressor',
    category: 'Video Tools',
    subcategory: 'Compressors',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Video Compressor tool running directly in your browser or securely on our servers.',
    icon: faVideo,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Video Compressor',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Video Compressor tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_VIDEO_COMPRESSOR_ID || 'video-compressor',
  },
  {
    id: 'video-manipulator',
    slug: 'video-manipulator',
    name: 'Video Manipulator',
    category: 'Video Tools',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Video Manipulator tool running directly in your browser or securely on our servers.',
    icon: faVideo,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Video Manipulator',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Video Manipulator tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_VIDEO_MANIPULATOR_ID || 'video-manipulator',
  },
  {
    id: 'video-trimmer',
    slug: 'video-trimmer',
    name: 'Video Trimmer',
    category: 'Video Tools',
    subcategory: 'Resizers',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Video Trimmer tool running directly in your browser or securely on our servers.',
    icon: faVideo,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Video Trimmer',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Video Trimmer tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_VIDEO_TRIMMER_ID || 'video-trimmer',
  },
  {
    id: 'word-counter',
    slug: 'word-counter',
    name: 'Word Counter',
    category: 'PDF & Documents',
    subcategory: 'Utilities',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Word Counter tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Word Counter',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Word Counter tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_WORD_COUNTER_ID || 'word-counter',
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    name: 'Word To PDF',
    category: 'PDF & Documents',
    subcategory: 'Converters',
    type: 'Free',
    isNew: true,
    isPopular: false,
    runs: '0',
    desc: 'High-quality Word To PDF tool running directly in your browser or securely on our servers.',
    icon: faFileLines,
    imageUrl: null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name: 'Word To PDF',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description: 'High-quality Word To PDF tool running directly in your browser or securely on our servers.',
    }),
    functionId: import.meta.env.VITE_APPWRITE_FUNCTION_WORD_TO_PDF_ID || 'word-to-pdf',
  },
];

const FALLBACK_TOOL_LOOKUP = Object.fromEntries(FALLBACK_TOOLS.map((tool) => [tool.slug, tool]));

function iconForTool(doc: any): IconDefinition {
  return TOOL_ICON_MAP[doc.category] || TOOL_ICON_MAP[doc.subcategory] || faCode;
}

function toCard(doc: any, viewsBySlug: Record<string, number> = {}): ToolCard {
  const slug = String(doc.slug || doc.$id || doc.id || '').trim();
  const fallback = FALLBACK_TOOL_LOOKUP[slug];
  const name = String(doc.name || fallback?.name || slug || 'Untitled Tool');
  const category = String(doc.category || fallback?.category || 'Developer Tools');
  const subcategory = String(doc.subcategory || fallback?.subcategory || 'General');
  const description = String(doc.description || doc.desc || fallback?.desc || '');
  const viewCount = viewsBySlug[slug] ?? Number(doc.runs || doc.views || 0);

  return {
    id: slug,
    slug,
    name,
    category,
    subcategory,
    type: doc.is_free === false || String(doc.type || '').toLowerCase() === 'pro' ? 'Pro' : 'Free',
    isNew: Boolean(doc.is_new),
    isPopular: Boolean(doc.is_popular ?? doc.isPopular),
    runs: String(viewCount),
    desc: description,
    icon: iconForTool(doc),
    imageUrl: doc.icon && /^https?:\/\//i.test(String(doc.icon)) ? String(doc.icon) : null,
    schemaMarkup: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      name,
      applicationCategory: category.replace(/ Tools$/i, 'Application'),
      operatingSystem: 'Web',
      description,
    }),
    functionId: doc.function_id || fallback?.functionId,
    tags: Array.isArray(doc.tags) ? doc.tags.map((tag: unknown) => String(tag)) : [],
  };
}

function buildCategoryCards(tools: ToolCard[]): CategoryCard[] {
  const grouped = new Map<string, Set<string>>();
  tools.forEach((tool) => {
    if (!grouped.has(tool.category)) grouped.set(tool.category, new Set());
    grouped.get(tool.category)!.add(tool.subcategory);
  });

  return [
    { name: 'All Tools', count: tools.length },
    ...Array.from(grouped.entries()).map(([name, subs]) => ({
      name,
      count: tools.filter((tool) => tool.category === name).length,
      sub: Array.from(subs),
    })),
  ];
}

function pickFeaturedTools(tools: ToolCard[]): ToolCard[] {
  return [...tools]
    .sort((left, right) => Number(right.isPopular) - Number(left.isPopular) || Number(right.isNew) - Number(left.isNew) || Number(right.runs) - Number(left.runs))
    .slice(0, 3);
}

export function useToolCatalog(): ToolCatalogState {
  const [state, setState] = useState<ToolCatalogState>({
    tools: FALLBACK_TOOLS,
    featuredTools: pickFeaturedTools(FALLBACK_TOOLS),
    categoryCards: buildCategoryCards(FALLBACK_TOOLS),
    loading: true,
  });

  useEffect(() => {
    let cancelled = false;

    const loadCatalog = async () => {
      if (!isAppwriteConfigured()) {
        if (!cancelled) {
          setState({
            tools: FALLBACK_TOOLS,
            featuredTools: pickFeaturedTools(FALLBACK_TOOLS),
            categoryCards: buildCategoryCards(FALLBACK_TOOLS),
            loading: false,
          });
        }
        return;
      }

      try {
        const [toolDocs, viewDocs] = await Promise.all([
          databases.listDocuments(DATABASE_ID, 'tools', [Query.orderAsc('name'), Query.limit(500)]),
          databases.listDocuments(DATABASE_ID, 'tool_views', [Query.limit(500)]),
        ]);

        const viewsBySlug = Object.fromEntries(
          (viewDocs.documents || []).map((doc: any) => [String(doc.tool_slug), Number(doc.count || 0)])
        );
        const tools = (toolDocs.documents || []).map((doc: any) => toCard(doc, viewsBySlug));

        if (!cancelled) {
          setState({
            tools,
            featuredTools: pickFeaturedTools(tools),
            categoryCards: buildCategoryCards(tools),
            loading: false,
          });
        }
      } catch {
        if (!cancelled) {
          setState({
            tools: FALLBACK_TOOLS,
            featuredTools: pickFeaturedTools(FALLBACK_TOOLS),
            categoryCards: buildCategoryCards(FALLBACK_TOOLS),
            loading: false,
          });
        }
      }
    };

    void loadCatalog();
    return () => {
      cancelled = true;
    };
  }, []);

  return state;
}
