import { Client, Databases, ID } from 'node-appwrite';
import dotenv from 'dotenv';

dotenv.config();

const client = new Client()
  .setEndpoint(process.env.APPWRITE_ENDPOINT)
  .setProject(process.env.APPWRITE_PROJECT_ID)
  .setKey(process.env.APPWRITE_API_KEY);

const db = new Databases(client);
const databaseId = process.env.DATABASE_ID || 'qofeno_db';

async function run() {
  console.log("Checking whats_new documents...");
  const list = await db.listDocuments(databaseId, 'whats_new');
  if (list.total === 0) {
    console.log("Seeding whats_new collection...");
    const initialItems = [
      {
        title: "Qofeno Platform Overhaul & Enhancements",
        body: "We have finalized a major update to Qofeno! Highlights include a 5-column responsive footer, Turnstile captcha setup, PayPal subscription models, and dynamic roadmaps fetched directly from the Appwrite server databases. Performance is optimized with standard prefers-reduced-motion animation freezes.",
        type: "product_update",
        author: "Mohd Zaheer Uddin",
        published: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      {
        title: "New Tool: JPG to PDF Converter Added",
        body: "A server-processed JPG to PDF converter is now available for all users! Upload bulk image documents and compress them into a single PDF instantly.",
        type: "new_tool",
        author: "Mohd Zaheer Uddin",
        published: true,
        created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString()
      },
      {
        title: "Fixed Cross-Origin Processed File Downloads",
        body: "Resolved a critical browser downloading issue. Processed files generated by Appwrite server storage buckets now download directly as local file objects on the client origin, eliminating browser cross-origin target blocks.",
        type: "fix",
        author: "Mohd Zaheer Uddin",
        published: true,
        created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString()
      }
    ];

    for (const item of initialItems) {
      await db.createDocument(databaseId, 'whats_new', ID.unique(), item);
      console.log(`Seeded whats_new post: ${item.title}`);
    }
  } else {
    console.log(`whats_new already contains ${list.total} documents.`);
  }
}

run().catch(console.error);
