/// <reference types="vite/client" />

interface ImportMetaEnv {
  readonly VITE_APPWRITE_ENDPOINT?: string;
  readonly VITE_APPWRITE_PROJECT_ID?: string;
  readonly VITE_APPWRITE_DATABASE_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_JSON_FORMATTER_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_WORD_COUNTER_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_BASE64_ENCODER_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_TEXT_CASE_CONVERTER_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_TRACK_EVENT_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_AUTH_WEBHOOK_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_PAYMENT_WEBHOOK_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_CREATE_DOWNLOAD_LINK_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_PDF_COMPRESSOR_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_PDF_MERGER_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_PDF_SPLITTER_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_PDF_TO_WORD_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_IMAGE_RESIZER_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_IMAGE_COMPRESSOR_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_IMAGE_CONVERTER_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_IMAGE_BG_REMOVER_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_VIDEO_COMPRESSOR_ID?: string;
  readonly VITE_APPWRITE_FUNCTION_VIDEO_TRIMMER_ID?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
